theme = "stack"
baseURL = "https://alexnash.dev/"
defaultContentLanguage = "en"
description = "A blog about tech, software projects, and engineering"

# pluralizeListTitles = "true" # hugo function useful for non-english languages, find out more in  https://gohugo.io/getting-started/configuration/#pluralizelisttitles

enableRobotsTXT = true
paginate = 10
summaryLength = 0

buildDrafts = false
buildFuture = false

googleAnalytics = "G-2VC8B41NDX"

[outputs]
  home = ["HTML", "RSS"]

[minify]
  [minify.tdewolff]
    minifyHTML = true

[params]
  hugoPipeImageMaxWidth = 2000
