theme = "stack"
baseURL = "https://alexnash.dev/"
defaultContentLanguage = "en"

# pluralizeListTitles = "true" # hugo function useful for non-english languages, find out more in  https://gohugo.io/getting-started/configuration/#pluralizelisttitles

enableRobotsTXT = true
paginate = 10
summaryLength = 0

buildDrafts = false
buildFuture = false

# googleAnalytics = "G-XXXXXXXXX"

[outputs]
  home = ["HTML", "RSS"]