# Configure main menu and social menu
# [[main]]
# identifier = "about"
# name = "About"
# url = "/about"
#
# [main.params]
# icon = "home"

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/nashalexander"
weight = 1

[social.params]
icon = "brand-github"

[[social]]
identifier = "email"
name = "Email"
url = "mailto:contact@alexnash.dev"
weight = 2

[social.params]
icon = "mail"